---
name: dist

on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - '*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: psf/black@stable

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-22.04", "windows-2022"]
        python_version:
        - '3.12'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
        architecture: ${{ matrix.architecture }}
    - name: Install deps
      run: |
        pip install -U pip
        pip install 'robotpy[all]<2026.0.0,>=2025.0.0b3' numpy pytest 'robotpy-ctre==2025.0.0' photonlibpy
    - name: Run tests
      run: bash run_tests.sh
      shell: bash
